name: 'Setup Mysql'
description: 'Start Mysql Server'
runs:
  using: 'composite'
  steps:
    - run: |
        mysql --version
        sudo systemctl start mysql
        mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u root -pubuntu -e 'CREATE DATABASE IF NOT EXISTS circle_test;'
        mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u root -pubuntu -e 'CREATE USER "alessandro"@"%" IDENTIFIED BY "ubuntu";'
        mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -u root -pubuntu -e 'GRANT ALL PRIVILEGES ON * . * TO "alessandro"@"%"; FLUSH PRIVILEGES;'
      shell: bash
